### ISSUE TITLE
Action fails if branch is already setup on amplify

### ISSUE THREAD

**Issue by daltonfury42** [yinlinchen/amplify-preview-actions#10] opened 2020-10-31 07:12 UTC
Sample Run with Error: https://github.com/SimplQ/simplQ-frontend/pull/401/checks?check_run_id=1335345160

I am probably facing this issue because I have configured only `deploy` and not `delete` for my repo, but still it will be nice if in the above mentioned scenario where the branch is already connected on amplify, we don't fail but resume at the line where we emitted error.

**Comment by yinlinchen** [comment] 2020-11-02 15:11
@daltonfury42 Can you please describe the steps to reproduce this behavior or terminal output if applicable. Thank you!

**Comment by voravor** [comment] 2021-03-26 22:16
We are also seeing that if the preview branch already exists in Amplify then subsequent runs of this action will appear as if it had failed back in the PR. Is there an option we are missing?

**Comment by yinlinchen** [comment] 2021-03-26 23:57
@voravor Can you describe the scenario about `preview branch already exist`?

At the beginning, there is no preview branch in the Amplify. After a new PR is created and submitted for review, with this setup, a preview branch will be created and exist in the Amplify automatically. 

1. If this PR has a new update through a push, it will update the exiting preview branch in the Amplify automatically. 
2. If this PR is approved and merged, it will delete the preview branch in the Amplify automatically.

Our [project](https://github.com/VTUL/dlp-access/pulls?q=is%3Apr+is%3Aclosed) uses above scenario more than six months. We haven't encounter this issue. 

Or, did you mean you deploy a branch in the Amplify first, so the branch already exists in the Amplify. Later, you update that branch with a PR with this setup?

**Comment by voravor** [comment] 2021-03-29 01:33
When a PR is created with the correct label, the preview branch is correctly created in Amplify. 

When new commits are added to this PR, the preview creation action is run again. This is sometimes resulting in a failure of the action.

`An error occurred (BadRequestException) when calling the CreateBranch operation: Failed to create branch. The branch PICO-4365-Create-Popup-Button-Alignment-is-Too-High already exists for the app ***`

Here's how it looks in the PR itself:
<img width="862" alt="Screen Shot 2021-03-28 at 9 29 20 PM" src="https://user-images.githubusercontent.com/184710/112776150-dacff080-900c-11eb-996b-23e16e251c5c.png">

Note: there is no error in Amplify. The build history for this PR / connected branch looks like this:
<img width="597" alt="Screen Shot 2021-03-28 at 9 32 26 PM" src="https://user-images.githubusercontent.com/184710/112776249-26829a00-900d-11eb-9f19-2e08129b00c8.png">

**Comment by yinlinchen** [comment] 2021-03-31 20:46
@voravor and @daltonfury42 could you please test if https://github.com/yinlinchen/amplify-preview-actions/pull/9/files from @sean-smith can resolve this issue? If it does, I am happy to merge that. The thing is, I am not able to reproduce this issue to test that. Thank you!

**Comment by rachelslurs** [comment] 2021-04-28 05:23
I'm seeing this too. @yinlinchen It looks like this PR would have fixed the issue,

To recreate issue:
1. Set your action to run `if: contains(github.event.pull_request.labels.*.name, 'Ready to Review')`
2. Open a pull request, add label "Ready to Review"
3. Add additional commit
4. See the check fail

**Comment by rachelslurs** [comment] 2021-04-28 05:25
![image](https://user-images.githubusercontent.com/1870406/116350845-9e84e100-a7c0-11eb-97d1-39a4fef96c50.png)

**Closed as completed** 2021-04-28 14:14 UTC

**Comment by voravor** [comment] 2021-04-28 17:01
At first glance I think the var `branch_exist` vs `branch_exists` usage https://github.com/yinlinchen/amplify-preview-actions/pull/9/files line 49-50 will cause problems?

> @voravor and @daltonfury42 could you please test if https://github.com/yinlinchen/amplify-preview-actions/pull/9/files from @sean-smith can resolve this issue? If it does, I am happy to merge that. The thing is, I am not able to reproduce this issue to test that. Thank you!
